---
openapi: 3.0.0
info:
  title: Lambda Integration API
  version: 1.0.0
paths:
  "/hello":
    get:
      summary: Say hello
      operationId: sayHello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
